language: php

sudo: false

env:
  global:
    - secure: "cY04rbEHY8Gra1rUvlXqDndO1c/a9pryeHY3rYq8ddEmqSfrSBYaK9ilbD9nr4xawomBjyxvWYpwxPuC8lzn0R50P2ytwspcgjwJLA6l9x5YPIzbYOikuGMUhql1qhyMVgkP4feP3DM+5U67jPcBaHONXa2hQ2U1LDG/Foq5d7NPsIIF5rYx+OLXwUVwFbsLIhDXFU1mKP/hpsD8aYIxeUpbtyLwd65ZsTZ37cviSLBrSevsKh7/icqYcK4vZcpMQOCy770H1kMeunpCqekVRH0/UodrdGCQFkwW36S9YklPgdzTBRovEBRto4LJov085DR/AKRdGnGxYTig8MtKVz0yXBxkXhKovLDGmm+QIkgREz1UBq08uJ9kqybZb7Fa9GzDsRfEwFSOvNSdMm2S6nz1MXNXOQOGlFwcliB7TKNpMMqupZNeosWFo5LPmX5k3pwZ5/CggQeKLgGKxY5IYV0kQ2gkqagNmM34AUimIoTuC+gWOfgYD0LIo2tEggWihMs3GAJqriv12pVPIFC5UYr55UfjVfDF700IaW91xQDUMBLhCg0ZlZp+eKG2EPgu5NmJS3de32A3Vlc904w8I/tUnyRFhJOX6kgfV4uZZnXZ0Hhd5+1hwMK/gpyzCDPxJ/aaP/b5jxM0lx6oLQCmJGJ+OTSw2WLhkvXveppHGFg="
    - secure: "iA2mwG9wMVeds0xzJdOMrZ4cTdCS893xYaMPrcRqXL5BdqYEbDsTetrAJSZr5kFvWwAh4JzTbEY73NnpxCZHdGGy10EXsGNP2+PfgCeMBUAkyRffowbLEVUGj/Ib2m8bnZHpu3YIlj4WXSwemmd1xz1SM4gFsbBfVWywgvrlTh+H9YyPNR5kaFnQCffGumX1F6/MNOzcchAP8qSGlID7usoJw6lFyQzD1QOO2d+k5pOAhyamFrhJWBAtVIgUZr3iO+m1WV5f4MZQJQBJgXeiZ35Wd7VfhCbCyT96QqsrnP5K8GUfwd4H1WymJAayQ6ln2Y8ZFRhVB1pNOKzgz8dCfIJkqsnsk/mOsXcgnYQPFu1Sc6Gyw9n7gouWRcPBEl6r9Yw9gBlCDPIlSSsM1sU3e5B2LzjYXFXXAcKlFmIQlG4s0ecMBEunCbQfqNpJsnofl1T4dJXdi2fiSmOgUHX5cHf2v0OY+oj61Ur27ZnQWIcxdMiu75CZx5TuKfWYgxsZ5JwDyow5Dq9wMxTek1szd/sRiNkL1Zh51rPqERhJFSIe0KlbCQUt/HkU8T+3CqoMqWaLhw47Se2XOvEwabtuqwuL827ufjPgf0BKZT3nCqRJDDvpKW9H9GciKIZQ3dS8MrYhN1W+VNvHFrt88TfjaI0WB7edhR+fzXuDyNka2fU="

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
      env: WITH_CS=true
    - php: 7.1
      env: WITH_COVERAGE=true
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - if [[ "$WITH_COVERAGE" != "true" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer validate
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - composer install --prefer-dist

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - mkdir -p build/logs

script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration=test/Unit/phpunit.xml; fi
  - vendor/bin/phpunit --configuration=test/Integration/phpunit.xml
  - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run; fi

after_success:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/test-reporter --coverage-report=build/logs/clover.xml; fi

notifications:
  email: false
